[workspace]
resolver = "2"
members = ["src/hyperlight-js", "src/js-host-api", "src/hyperlight-js-runtime", "src/hyperlight-js-common"]
exclude = ["src/hyperlight-js-runtime/tests/fixtures"]

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
repository = "https://github.com/hyperlight-dev/hyperlight-js"
readme = "README.md"

[workspace.dependencies]
hyperlight-guest-bin = { git = "https://github.com/hyperlight-dev/hyperlight", rev = "fe19bf0645b9969752cf215669980fa9075dc953", features = ["libc"] }
hyperlight-host = { git = "https://github.com/hyperlight-dev/hyperlight", rev = "fe19bf0645b9969752cf215669980fa9075dc953", default-features = false }
hyperlight-common = { git = "https://github.com/hyperlight-dev/hyperlight", rev = "fe19bf0645b9969752cf215669980fa9075dc953", default-features = false }
hyperlight-guest = { git = "https://github.com/hyperlight-dev/hyperlight", rev = "fe19bf0645b9969752cf215669980fa9075dc953" }

hyperlight-js = { version = "0.4.0", path = "src/hyperlight-js" }
hyperlight-js-runtime = { version = "0.4.0", path = "src/hyperlight-js-runtime" }
hyperlight-js-common = { version = "0.4.0", path = "src/hyperlight-js-common" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
