# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Create a Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write # needed to create a release

jobs:
  build:
    uses: ./.github/workflows/dep_build.yml
    secrets: inherit
    with:
        environment: release

  benchmarks:
    uses: ./.github/workflows/dep_benchmarks.yml
    secrets: inherit
    with:
        download-benchmarks: true
        upload-benchmarks: true
        environment: release
  
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Set version
        id: set-version
        shell: bash
        run: |
          git fetch --tags || true
          # Extract the version number from the branch name, which is expected to be in the format 'release/vX.Y.Z'
          # if not, default to '0.0.0' to avoid errors in subsequent steps
          if [[ "${GITHUB_REF}" =~ refs/heads/release/v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            version="${BASH_REMATCH[1]}"
          else
            version="0.0.0"
          fi
          echo "Setting version to 'v$version'"
          echo "version=$version" >> $GITHUB_OUTPUT

  create-gh-release:
    needs: [build, benchmarks, set-version]
    environment: release
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/release/') }}

    steps:
      - name: Download benchmarks (Windows)
        uses: actions/download-artifact@v8
        with:
          name: benchmarks_Windows_whp
          path: benchmarks_Windows_whp

      - name: Download benchmarks (Linux kvm)
        uses: actions/download-artifact@v8
        with:
          name: benchmarks_Linux_kvm
          path: benchmarks_Linux_kvm

      - name: Download benchmarks (Linux hyperv3)
        uses: actions/download-artifact@v8
        with:
          name: benchmarks_Linux_hyperv3
          path: benchmarks_Linux_hyperv3
  
      - name: Archive benchmarks
        run: |
          tar -zcvf benchmarks_Windows_whp.tar.gz benchmarks_Windows_whp
          tar -zcvf benchmarks_Linux_kvm.tar.gz benchmarks_Linux_kvm
          tar -zcvf benchmarks_Linux_hyperv3.tar.gz benchmarks_Linux_hyperv3

      - name: Create GH Release
        run: |
            gh release create ${{ needs.set-version.outputs.version }} \
              --generate-notes \
              benchmarks_Windows_whp.tar.gz \
              benchmarks_Linux_kvm.tar.gz \
              benchmarks_Linux_hyperv3.tar.gz
        env:
            GH_TOKEN: ${{ github.token }}

  publish-npm-packages:
    needs: [build, benchmarks, set-version]
    uses: ./.github/workflows/npm-publish.yml
    with:
      version: ${{ needs.set-version.outputs.version }}
      dry-run: ${{ !contains(github.ref, 'refs/heads/release/') }}

  publish-cargo-crates:
    needs: [build, benchmarks, set-version]
    uses: ./.github/workflows/cargo-publish.yml
    with:
      version: ${{ needs.set-version.outputs.version }}
      dry-run: ${{ !contains(github.ref, 'refs/heads/release/') }}
